Hämtar pandas för att läsa, hantera och analysera dataset. 
Hämtar matplotlib för att skapa grafer och visualiseringar.

In [4]:
import pandas as pd # hämta pandas bibliotek för att hantera data
import matplotlib.pyplot as plt

In [2]:
print("EDA Ghalia starter")

EDA Ghalia starter

Hämtar filmdata från API, ansluter till API och hämtar 100 populära filmer.

In [2]:
import sys
sys.path.append('/Users/ghaliaghazal/Documents/Grupp7_Datavisualisering_DE_UX')


from src.etl.extract import Extract

extractor = Extract()
data = extractor.fetch_movies()

len(data) # räknar hur många filmer som hämtades
data[0]

{'adult': False,
 'backdrop_path': '/iN41Ccw4DctL8npfmYg1j5Tr1eb.jpg',
 'genre_ids': [878, 12, 14],
 'id': 83533,
 'original_language': 'en',
 'original_title': 'Avatar: Fire and Ash',
 'overview': "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
 'popularity': 485.0972,
 'poster_path': '/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg',
 'release_date': '2025-12-17',
 'title': 'Avatar: Fire and Ash',
 'video': False,
 'vote_average': 7.373,
 'vote_count': 2400}

In [3]:
len(data)

100

In [5]:
df = pd.DataFrame(data) # gör om listan med 100 filmer som en tabell
df .head() # visar de 5 första filmerna i tabellen

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/iN41Ccw4DctL8npfmYg1j5Tr1eb.jpg,"[878, 12, 14]",83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,485.0972,/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg,2025-12-17,Avatar: Fire and Ash,False,7.373,2400
1,False,/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg,"[16, 12, 14, 10751, 35]",1226863,en,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,317.0939,/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg,2026-04-01,The Super Mario Galaxy Movie,False,6.953,275
2,False,/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg,"[10751, 35, 12, 16, 14]",502356,en,The Super Mario Bros. Movie,"While working underground to fix a water main,...",225.7027,/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg,2023-04-05,The Super Mario Bros. Movie,False,7.587,10440
3,False,/1RgPyOhN4DRs225BGTlHJqCudII.jpg,"[16, 28, 14]",1311031,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,The Demon Slayer Corps are drawn into the Infi...,120.4844,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,Demon Slayer: Kimetsu no Yaiba Infinity Castle,False,7.670,780
4,False,/l8rKKMU2M9dDULO9CEtDNdWAEUJ.jpg,"[878, 27, 14]",1159831,en,The Bride!,A lonely Frankenstein travels to 1930s Chicago...,91.1371,/lV8YHwGkYZsm6EfIqnhaSz2avKt.jpg,2026-03-04,The Bride!,False,6.300,218

# Connect and query
Hämtar data från databasen, ansluter till DuckDB och hämtar alla filmer som en tabell.

In [5]:
import duckdb
# anslut till databasen
con = duckdb.connect('/Users/ghaliaghazal/Documents/Grupp7_Datavisualisering_DE_UX/data/db/movies.duckdb')
# hämta alla filmer som en tabell
df = con.execute("SELECT * FROM movies").df()
df.head()

,movie_id,title,release_date,rating,popularity,release_year
0,83533,Avatar: Fire and Ash,2025-12-17,7.373,485.097198,2025
1,1226863,The Super Mario Galaxy Movie,2026-04-01,6.953,317.093903,2026
2,502356,The Super Mario Bros. Movie,2023-04-05,7.587,225.702698,2023
3,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025-07-18,7.670,120.484398,2025
4,1159831,The Bride!,2026-03-04,6.300,91.137100,2026