Hämtar pandas för att läsa, hantera och analysera dataset. 
Hämtar matplotlib för att skapa grafer och visualiseringar.

In [9]:
import pandas as pd # hämta pandas bibliotek för att hantera data
import matplotlib.pyplot as plt

In [10]:
print("EDA Ghalia starter")

EDA Ghalia starter

Hämtar filmdata från API, ansluter till API och hämtar 100 populära filmer.

In [11]:
import sys
sys.path.append('/Users/ghaliaghazal/Documents/Grupp7_Datavisualisering_DE_UX')


from src.etl.extract import Extract

extractor = Extract()
data = extractor.fetch_movies()

len(data) # räknar hur många filmer som hämtades
data[0]

{'adult': False,
 'backdrop_path': '/iN41Ccw4DctL8npfmYg1j5Tr1eb.jpg',
 'genre_ids': [878, 12, 14],
 'id': 83533,
 'original_language': 'en',
 'original_title': 'Avatar: Fire and Ash',
 'overview': "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.",
 'popularity': 485.0972,
 'poster_path': '/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg',
 'release_date': '2025-12-17',
 'title': 'Avatar: Fire and Ash',
 'video': False,
 'vote_average': 7.373,
 'vote_count': 2400}

In [12]:
len(data)

100

In [13]:
df = pd.DataFrame(data) # gör om listan med 100 filmer som en tabell
df .head() # visar de 5 första filmerna i tabellen

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/iN41Ccw4DctL8npfmYg1j5Tr1eb.jpg,"[878, 12, 14]",83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,485.0972,/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg,2025-12-17,Avatar: Fire and Ash,False,7.373,2400
1,False,/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg,"[16, 12, 14, 10751, 35]",1226863,en,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,317.0939,/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg,2026-04-01,The Super Mario Galaxy Movie,False,6.953,275
2,False,/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg,"[10751, 35, 12, 16, 14]",502356,en,The Super Mario Bros. Movie,"While working underground to fix a water main,...",225.7027,/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg,2023-04-05,The Super Mario Bros. Movie,False,7.587,10440
3,False,/1RgPyOhN4DRs225BGTlHJqCudII.jpg,"[16, 28, 14]",1311031,ja,劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来,The Demon Slayer Corps are drawn into the Infi...,120.4844,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,Demon Slayer: Kimetsu no Yaiba Infinity Castle,False,7.670,780
4,False,/l8rKKMU2M9dDULO9CEtDNdWAEUJ.jpg,"[878, 27, 14]",1159831,en,The Bride!,A lonely Frankenstein travels to 1930s Chicago...,91.1371,/lV8YHwGkYZsm6EfIqnhaSz2avKt.jpg,2026-03-04,The Bride!,False,6.300,218

# Connect and query
Hämtar data från databasen, ansluter till DuckDB och hämtar alla filmer som en tabell.

In [14]:
import duckdb
# anslut till databasen
con = duckdb.connect('/Users/ghaliaghazal/Documents/Grupp7_Datavisualisering_DE_UX/data/db/movies.duckdb')
# hämta alla filmer som en tabell
df = con.execute("SELECT * FROM movies").df()
df.head()

,movie_id,title,release_date,rating,popularity,release_year
0,83533,Avatar: Fire and Ash,2025-12-17,7.373,485.097198,2025
1,1226863,The Super Mario Galaxy Movie,2026-04-01,6.953,317.093903,2026
2,502356,The Super Mario Bros. Movie,2023-04-05,7.587,225.702698,2023
3,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025-07-18,7.670,120.484398,2025
4,1159831,The Bride!,2026-03-04,6.300,91.137100,2026

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      100 non-null    int32
 1   title         100 non-null    str
 2   release_date  100 non-null    datetime64[us]
 3   rating        100 non-null    float32
 4   popularity    100 non-null    float32
 5   release_year  100 non-null    int32
dtypes: datetime64[us](1), float32(2), int32(2), str(1)
memory usage: 3.3 KB

In [27]:
df.describe()

           movie_id         release_date      rating  popularity  release_year
count  1.000000e+02                  100  100.000000  100.000000    100.000000
mean   4.770132e+05  2014-01-23 09:36:00    7.218700   32.291203   2013.470000
min    2.200000e+01  1939-08-15 00:00:00    0.000000   11.499900   1939.000000
25%    1.612250e+03  2006-05-14 06:00:00    6.851000   14.136750   2005.750000
50%    2.886095e+05  2017-03-12 00:00:00    7.314000   18.246600   2017.000000
75%    9.832312e+05  2025-04-28 00:00:00    7.867000   25.481774   2025.000000
max    1.575337e+06  2026-11-08 00:00:00    8.533000  485.097198   2026.000000
std    5.281319e+05                  NaN    1.064552   59.946815     15.059783

In [28]:
df.describe().round(2)

         movie_id         release_date  rating  popularity  release_year
count      100.00                  100  100.00      100.00        100.00
mean    477013.15  2014-01-23 09:36:00    7.22       32.29       2013.47
min         22.00  1939-08-15 00:00:00    0.00       11.50       1939.00
25%       1612.25  2006-05-14 06:00:00    6.85       14.14       2005.75
50%     288609.50  2017-03-12 00:00:00    7.31       18.25       2017.00
75%     983231.25  2025-04-28 00:00:00    7.87       25.48       2025.00
max    1575337.00  2026-11-08 00:00:00    8.53      485.10       2026.00
std     528131.93                  NaN    1.06       59.95         15.06

In [30]:
df.isnull() # visa om det finns några tomma värden i varje kolumn

    movie_id  title  release_date  rating  popularity  release_year
0      False  False         False   False       False         False
1      False  False         False   False       False         False
2      False  False         False   False       False         False
3      False  False         False   False       False         False
4      False  False         False   False       False         False
..       ...    ...           ...     ...         ...           ...
95     False  False         False   False       False         False
96     False  False         False   False       False         False
97     False  False         False   False       False         False
98     False  False         False   False       False         False
99     False  False         False   False       False         False

[100 rows x 6 columns]

In [31]:
df.isnull() .sum()

movie_id        0
title           0
release_date    0
rating          0
popularity      0
release_year    0
dtype: int64